services:
  uptime-kuma:
    image: ghcr.io/GrantM28/uptime:latest
    container_name: madi-monitor
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - "3021:3001"
